services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/testtest
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
        - ./redis/data:/data
    command: redis-server