name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  code-validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.6
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.6"

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --group=dev

    - name: Type checking
      run: mypy .

    - name: Run commit message linter
      uses: wagoid/commitlint-github-action@v6